language: python
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.4
    - pypy
install:
    - travis_retry pip install coverage coveralls
script:
    - coverage run --source=profilehooks test_profilehooks.py
after_success:
    - coveralls
notifications:
    email: false
